### ISSUE TITLE
Julia 0.6

### ISSUE THREAD

**Issue by femtotrader** [dysonance/Temporal.jl#10]
Julia 0.6 is out.
https://julialang.org/blog/2017/06/julia-0.6-release

https://github.com/dysonance/Temporal.jl/blob/master/.travis.yml#L6
https://github.com/dysonance/Temporal.jl/blob/master/REQUIRE#L1
https://github.com/dysonance/Temporal.jl/blob/master/appveyor.yml#L3

Running unit tests display a lot of warnings and raise a lot of exceptions.

**Comment by dysonance** [comment]
@femtotrader Thanks for the heads up, will take a look.

Nice to have 0.6 out, just haven't had as much time as I'd like to get back to these side projects lately (work been extra busy...also just got married 😃).

**Comment by dysonance** [comment]
Pushed some updates, now just waiting for published changes to get merged into METADATA repo. Hopefully the issues you were experiencing should be resolved. I'm gonna close this issue for now, feel free to reopen if problems don't go away.

**Comment by femtotrader** [comment]
Congratulations @dysonance for your wedding.

It's a good idea to avoid warnings because in a next Julia release this code will be broken.

**Comment by femtotrader** [comment]
I'm trying https://github.com/attobot/attobot for my package release.

**Comment by dysonance** [comment]
I think I've mostly taken care of these version transition issues. @femtotrader I'm gonna close this issue for now, just let me know if you're continuing to see warnings when using Julia v0.6 and we can re-open.
