### ISSUE TITLE
Implement a shift function

### ISSUE THREAD

**Issue by femtotrader** [dysonance/Temporal.jl#11]
Hello,

a shift function similar to https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.shift.html could be useful.

A `pct_chg` function could be useful also
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pct_change.html

Kind regard

PS: could help https://github.com/dysonance/Temporal.jl/issues/1

**Comment by dysonance** [comment]
I believe the `lag` function is what you're probably looking for, though I can quickly add a `shift` method to just alias the `lag` function.

As for percentage changes, you can do `diff(log(X))` for continuous, or `diff(X, pad=true, padval=NaN) ./ X` for discrete.

This does indicate another need with docs though, which is just the need to get more of the basic functionality documented somewhere.

**Comment by dysonance** [comment]
Pull request to address this opened here: https://github.com/dysonance/Temporal.jl/pull/15

**Comment by dysonance** [comment]
PR above has been merged, closing now, let me know if more to be done.
