### ISSUE TITLE
Better doc

### ISSUE THREAD

**Issue by femtotrader** [dysonance/Temporal.jl#14]
Following https://github.com/dysonance/Temporal.jl/issues/12#issuecomment-348621423 
porting documentation to [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) may be considered
A second step could be to improve doc and work on better docstrings, and maybe doctests

**Comment by femtotrader** [comment]
Most of content of [README.md](https://github.com/dysonance/Temporal.jl/blob/master/README.md) should be moved into docs directory

**Comment by femtotrader** [comment]
That's probably a good issue for #hacktoberfest

**Comment by dysonance** [comment]
Documentation has been enhanced and the README has been ported to docs. Closing this now as the bulk of this is done and further refining will continue to be a WIP.
