### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by JeremieGauthier** [dysonance/Temporal.jl#35]
Hello Mr. Amos,

My name is Jeremie Gauthier. I am working in the field of high-frequency trading with 2 Ph.D students in machine learning. (Sorry, I didn't find another way to communicate with you)

I have already created a python program which is able to reformat the full market depth into the limit order book (i.e. bid, ask, limit, market and cancellation orders) with a certain time window. I am now interested in extending that code in order to get more relevant data to feed a classification model.

My attention is focused on the following article: https://arxiv.org/pdf/1810.10845.pdf

Can you help? The project is roughly programming in python.

**Comment by dysonance** [comment]
Hey @JeremieGauthier, thanks for reaching out. Could you be more specific about what kind of help you are looking for? While I have a good amount of experience working with time series data in Python, this repository is specifically focused on a time series implementation for the Julia language. So if you're looking for help converting Python data into a corresponding Julia structure, then I can probably provide some guidance on using this Temporal package.

If you're looking for more general assistance to help move your research project forward generally, I would still be happy to help where I might be able, but I would need more information on what you're looking for.

For future reference, if you're interested in reaching to me directly about things like this, feel free to connect with me and drop me a message on LinkedIn (profile [here](https://www.linkedin.com/in/jacobamos/)) or Twitter (profile [here](https://twitter.com/jamos125)).

**Comment by JeremieGauthier** [comment]
Hello Jacob,

Sorry, I can't reach you through LinkedIn or Twitter for the simple reason that I don't use those services.

The project has nothing to do with Julia or Temporal.jl. I have already a python program which is able to deal with the full market depth and create features for a classification model (HFT). I need to extend that code to add more relevant features.

I would be interested in hiring you. Let me know if you can help.

My email is gauthier.jeremie.1(at)gmail.com.

Jeremie Gauthier
