### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by JeremieGauthier** [dysonance/Temporal.jl#36]
Hello Jacob,

Sorry, I can't reach you through LinkedIn or Twitter for the simple reason that I don't use those services.

The project has nothing to do with Julia or Temporal.jl. I have already a python program which is able to deal with the full market depth and create features for a classification model (HFT). I need to extend that code to add more relevant features.  

I would be interested in hiring you. Let me know if you can help.

My email is gauthier.jeremie.1(at)gmail.com. 

Jeremie Gauthier

**Comment by dysonance** [comment]
Hi Jeremie,

While I would be open to assisting you with your research as I am able in my spare time, I am not currently interested in a new position professionally. If you would like to reach out to me directly via email about research collaboration, I have added my email address to my GitHub profile.

Regards,
Jacob
