### ISSUE TITLE
Can not install "Temporal.jl" with latest "Plots(v1.6.4)" and "RecipesBase" !

### ISSUE THREAD

**Issue by nuclear718** [dysonance/Temporal.jl#45]
### Can not install "Temporal.jl" with latest "Plots(v1.6.4)" and "RecipesBase" !

**`Pkg.add("Temporal")`**

**My versioninfo()**
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 3600X 6-Core Processor             
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA.EXECUTABLEPATH = C:\Users\USER\AppData\Local\Julia-1.3.1\bin\ & set JULIA_NUM_THREADS=12 & julia.exe
  JULIA_NUM_THREADS = 12

**The return message as below:**
  Resolving package versions...
Unsatisfiable requirements detected for package Plots [91a5bcdd]:
 Plots [91a5bcdd] log:
 ├─possible versions are: [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.4] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.4]
 ├─restricted by compatibility requirements with FixedPointNumbers [53c48c17] to versions: [0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.4] or uninstalled, leaving only versions: [0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.4]
 │ └─FixedPointNumbers [53c48c17] log:

**Comment by dysonance** [comment]
Hi @nuclear718, thanks for the heads up and the reminder that the latest package needs to be published to the general registry. I have released v0.8.0 and it looks like it should be merged in the next round of releases. Links below if you'd like to track the progress and be notified when the updates published so you can get the right version to fix your issue. Going to close for now, feel free to reopen if the issue persists after the updates are published.

https://github.com/JuliaRegistries/General/pull/21429

https://github.com/dysonance/Temporal.jl/releases/tag/v0.8.0
