### ISSUE TITLE
Update HTTP version

### ISSUE THREAD

**Issue by Arkoniak** [dysonance/Temporal.jl#47]
Current version of `Temporal.jl` uses HTTP 0.8. Current version of HTTP is 0.9, so usage of Temporal.jl is degrading all other packages. Can we bump HTTP to 0.9?

**Comment by dysonance** [comment]
I just released an update Temporal version with the HTTP dependency upgraded, so this should be good to go.

- Temporal release: https://github.com/dysonance/Temporal.jl/releases/tag/v0.8.1
- Registry pull request: JuliaRegistries/General#38480

**Comment by Arkoniak** [comment]
Thank you!
