### ISSUE TITLE
add plotting functionality!

### ISSUE THREAD

**Issue by dysonance** [dysonance/Temporal.jl#9]
It looks like [Plots.jl](https://github.com/JuliaPlots/Plots.jl) now support precompilation. Since adding a Plots dependency would have kept Temporal from precompiling (the only reason that these features were not yet added), it could well now be time to implement plotting recipes.

(However, if it goes back to not precompiling, then Temporal would no longer precompile. This is something that should be watched very closely.)

**Comment by femtotrader** [comment]
With @davidanthoff work on [integration of Temporal with IterableTables](https://github.com/dysonance/Temporal.jl/issues/3#issuecomment-307113195) it shouldn't be too hard to add plotting features.

**Comment by davidanthoff** [comment]
So what should work right now is that you can pass a ``TS`` to either Gadfly or VegaLite instead of a ``DataFrame``. I haven't integrated with Plots.jl because that is slightly more involved, but it is on my road map.

**Comment by ChrisRackauckas** [comment]
You don't need Plots.jl as a dependency. Just create recipes. You never should depend on Plots.jl itself.

**Comment by dysonance** [comment]
@ChrisRackauckas Thanks for the tip, made that change and pushed commits to METADATA, so hopefully plotting functionality with Plots.jl should be available publicly soon. Apologies for my ignorance in not realizing this was the proper way to integrate this functionality.
